name: Deployment pipeline

on: #event triggers
  push:
    branches:
      - main

jobs: # jobs executed when event triggered
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install backend
        run: npm install  
      - name: install frontend
        run: cd frontend && npm install && cd ..
      # - name: build backend
      #   run: npm run build
      - name: build frontend
        run: npm run build:linux
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "calm-crag-29470" #Must be unique in Heroku
          heroku_email: "nroovers@gmail.com"

