name: Deployment pipeline

on: #event triggers
  push:
    branches:
      - main

jobs: # jobs executed when event triggered
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: install backend
        run: npm install
      - name: lint backend
        run: npm run lint
      - name: test backend
        run: npm run test
      - name: install frontend
        run: cd frontend && npm install
      - name: lint frontend
        run: cd frontend && npm run lint
      - name: build frontend
        run: cd frontend && npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
      - name: copy frontent build folder 
        run: cp -v -R frontend/build build
      - name: git config
        run: git config --global user.email "nroovers@gmail.com" && git config --global user.name "nroovers"
      - name: git add build folder
        run: git add build && git commit -m "commit build for Heroku" && git push origin main:main
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.8.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "calm-crag-29470" #Must be unique in Heroku
          heroku_email: "nroovers@gmail.com"

